### ISSUE TITLE
error: ‘class caffe::LayerParameter’ has no member named ‘hashing_loss_param’

### ISSUE THREAD

**Issue by zqaidwj1314** [lhmRyan/deep-supervised-hashing-DSH#6]
Dear authors,
when I am trying to run the code, I got the following error "error: ‘class caffe::LayerParameter’ has no member named ‘hashing_loss_param’". I wonder is this the problem of the caffe version? Would you please tell me which caffe you used?

**Comment by lhmRyan** [comment]
Hi. In this repository, we slightly modified the orginal version of caffe. As a result, you need to download everything in this repo, and compile these codes, instead of the orginal caffe.

BTW. You can see the definition of "hashing_loss_param" in caffe.proto.

**Comment by liuyuying0829** [comment]
Dear authors,
when i  follow the instructions on "http://caffe.berkeleyvision.org/installation.html" to compile the source code, when i set "USE_CUDNN := 1",i got the error: few arguements for cudnn::createPoolingDesc ,i compare  the same file with caffe and copy the caffe's code and then compile successful. and then i known this problem is caused by the version of CuDnn . So i set"#USE_CUDNN := 1",then i can "make pycaffe" and "make all" ,but when i want to "make test",i got the error "no matching function for call to ReadImageToDatum and ReadFileToDatum",i can't resolve this problem, can you give me some advise ?
